program = { statement } EOF ;

expression = literal_expression
            | operator_expression ;

literal_expression = literal ;
operator_expression = assignment_expression
            | comparsion_expression
            | arithmetic_expression
            | logical_expression
            | negation_expression 
            | type_cast_expression ;

assignment_expression = expression "=" expression ;

comparsion_expression = expression "==" expression
            | expression "!=" expression
            | expression ">" expression
            | expression "<" expression
            | expression ">=" expression
            | expression "<=" expression ;

arithmetic_expression = expression "+" expression
            | expression "-" expression
            | expression "*" expression
            | expression "/" expression
            | expression "%" expression ;

logical_expression = expression "&&" expression
            | expression "||" expression ;

negation_expression = "-" expression
            | "!" expression ;


statement =  et_statement
            | const_statement
            | expression_statement ;

let_statement = "let" identifier [ ":" type ] [ "=" expression ] ;
const_statement = "const" identifier [ ":" type ] "=" expression ;
expression_statement = expression ;

literal = integer_literal
          | float_literal
          | character_literal
          | string_literal
          | boolean_literal ;

integer_literal = decimal_integer
                | hexadecimal_integer
                | binary_integer
                | octal_integer ;

decimal_integer = digit { digit } ;
hexadecimal_integer = "0" ( "x" | "X")  hex_digit { hex_digit } ;
binary_integer = "0" ( "b" | "B" ) binary_digit { binary_digit } ;
octal_integer = "0" ( "o" | "O" ) octal_digit { octal_digit } ;
float_literal = decimal_integer "." decimal_integer [ scientific_notation ]
              | decimal_integer scientific_notation ;
scientific_notation = ( "e" | "E" ) [ "+" | "-" ] decimal_integer ;

float_literal = integer_literal "." integer_literal ;
character_literal = "'" character  "'" ";" ;
string_literal = """ { character } """ ";" ;
boolean_literal = "true" | "false" ;

character = printable | escape_sequence ;
printable = alpha | digit | symbol | space ;
alpha = "a" ... "z" | "A" ... "Z" ;
digit = "0" ... "9";
hex_digit = digit | "a" ... "f" | "A" ... "F" ;
binary_digit = "0" | "1" ;
octal_digit = "0" ... "7" ;
symbol = "!" ... "/" | ":" ... "@" | "[" ... "`" | "{" ... "~" ;
underscore = "_" ;
escape_sequence = "\\" ( "n" | "t" | "r" | "\"" | "'" | "\\" ) ;
space = " " ;

identifier = ( alpha | "_" ) { ( alpha | digit | "_" ) } ;